kind: pipeline
name: blog

steps:
- build:
    image: cbrgm/drone-hugo:latest
    validate: true
    output: public

- publish:
    image: appleboy/drone-git-push
    branch: master
    remote: git@github.com:dohq/dohq.github.io.git
    force: false
    commit: true
    path: public/
