languageCode = "en-US"
contentdir = "content"
publishdir = "public"
baseurl = "https://dohq.github.io/"
canonifyurls = true
title = "やるだけやる"
theme = "hugo-gentoo-theme"
copyright = "2017 R.Maejima"
enableGitInfo = true

[author]
  author = "R.Maejima"
  gaid = "UA-11120276-5"

# TopMenu
[[menu.global]]
  url = "/tags/"
  name = "Tags"
  weight = 1

[[menu.global]]
  url = "/categories/"
  name = "categories"
  weight = 2

[[menu.footer]]
  url = "/about/"
  name = "About"
  weight = 3
