baseURL = "https://blog.dohq.dev/"
title = "やるだけやる"
theme = "temple"
languageCode = "en-us"
copyright = "2017 R.Maejima"
pygmentsStyle = "friendly"
pygmentsCodeFences = true

[params]
  dateformatpretty = "2006-01-02"
  toc = true

[author]
  author = "R.Maejima"
  gaid = "UA-11120276-5"
  github = "dohq"
  twitter = "dohq"

[taxonomies]
  tag = "tags"
  category = "categories"
