baseURL = "https://blog.dohq.dev/"
title = "やるだけやる"
theme = "temple"
languageCode = "en-us"
copyright = "2017 R.Maejima"

[params]
  highlight = true
  topmenu = "about"
  hjslangs = ["go", "vim", "dos"]

[author]
  author = "R.Maejima"
  gaid = "UA-11120276-5"
  github = "dohq"
  email = "dorastone@gmail.com"
  twitter = "dohq"

[taxonomies]
  tag = "tags"
  category = "categories"
