languageCode = "en-US"
contentdir = "content"
publishdir = "public"
baseurl = "https://dohq.github.io/"
canonifyurls = true
title = "やるだけやる"
theme = "hugo-gentoo-theme"
copyright = "2017 R.Maejima"
enableGitInfo = true

[author]
  author = "R.Maejima"
  gaid = "UA-11120276-5"

# TopMenu
[[menu.top]]
  url = "/tags/"
  name = "Tags"
  weight = 1

[[menu.top]]
  url = "/categories/"
  name = "categories"
  weight = 2

[[menu.top]]
  url = "/about/"
  name = "About"
  weight = 3

# BottomMenu
[[menu.bottom]]
	url = "/contact/"
	name = "Contact"
	weight = 1

[[menu.bottom]]
	url = "//github.com/dohq/"
	name = "GitHub"
	weight = 2

[[menu.bottom]]
	url = "//twitter.com/dohq"
	name = "Twitter"
	weight = 3
