baseURL = "https://blog.dohq.dev/"
title = "やるだけやる"
theme = "temple"
languageCode = "en-us"
copyright = "2017 R.Maejima"
pygmentsStyle = "friendly"
pygmentsCodeFences = true

[params]
  dateformatpretty = "2006-01-02"
  toc = true

[author]
  author = "R.Maejima"
  gaid = "UA-11120276-5"
  github = "dohq"
  twitter = "dohq"

[taxonomies]
  tag = "tags"
  category = "categories"

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+)$']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
